name: Deploy with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_APP }} .
          docker push ${{ secrets.DOCKERHUB_APP }}

      - name: Access Server and Run Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWD }}
          script: |
            cd /home/backend
            git fetch
            git reset --hard origin/main
            docker pull ${{ secrets.DOCKERHUB_APP }}
            docker-compose -f "./docker-compose.yml" kill app
            docker-compose -f "./docker-compose.yml" up -d app
            docker image prune -f